apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
- namespace.yaml
images:
- name: gcr.io/heptio-images/ks-guestbook-demo
  newName: docker.io/mizzy/hello
  newTag: 0.1
